In [1]:
##data encoding
#1 Nominal/OHE encoding
#2 Label and Ordinal Encoding 
#3 Target Guided ordinal encoding

In [18]:
#1nominal 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df= pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [19]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [20]:
#create the instance of Onehotenocder
encoder=OneHotEncoder()

In [23]:
#perform fit and transfrm
encoded=encoder.fit_transform(df[['color']]).toarray()

In [24]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [25]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [26]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [30]:
## for new data
encoder.transform([['blue']]).toarray()

c:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])